inherit_from: .rubocop_todo.yml
require: 
    - rubocop-rails
    - rubocop-faker
    - rubocop-rspec
inherit_gem:
    rubocop-shopify: rubocop.yml

AllCops:
    Exclude:
        - 'db/migrate/20200829032052_create_image_tags.rb'
        - 'app/graphql/loaders/has_many_loader.rb'
        - 'app/graphql/loaders/record_loader.rb'
