# Types Module generated by GraphQL-Ruby
module Types
  # The ImageType is the GraphQL type for the Image model
  class ImageType < Types::BaseObject
    description 'A type that represents a single Image entity.'
    field :id, ID, null: false
    field :title, String, null: false
    field :description, String, null: false
    field :price, Float, null: false
    field :attached_image_url, String, null: false
    field :tags, [Types::TagType], null: false
    field :user, Types::UserType, null: false
  end

  def tags
    Loaders::HasManyLoader.for(Tag, :tags).load(object)
  end

  def user
    RecordLoader.for(User).load(object.user_id)
  end
end
