# Types Module generated by GraphQL-Ruby
module Types
  # The PurchaseType is the GraphQL type for the Purchase model
  class PurchaseType < Types::BaseObject
    description 'A type that represents a single Purchase entity.'
    field :id, ID, null: false
    field :title, String, null: false
    field :description, String, null: false
    field :cost, Float, null: false
    field :attached_image_url, String, null: false
    field :user, Types::UserType, null: false
    field :merchant, Types::UserType, null: false
  end

  def user
    RecordLoader.for(User).load(object.user_id)
  end

  def merchant
    RecordLoader.for(User).load(object.merchant_id)
  end
end
