module Types
  # QueryType is generated by GraphQL-Ruby
  class QueryType < Types::BaseObject
    field :profile, resolver: Queries::Profile
    field :user, resolver: Queries::User
    field :users, resolver: Queries::Users
    field :tags, resolver: Queries::Tags
  end
end
