# Types Module generated by GraphQL-Ruby
module Types
  # The TagType is the GraphQL type for the Tag model
  class TagType < Types::BaseObject
    description 'A type that represents a single Tag entity.'
    field :id, ID, null: false
    field :name, String, null: false
    field :images, [Types::ImageType], null: false
  end

  def images
    Loaders::HasManyLoader.for(Image, :images).load(object)
  end
end
