# Types Module generated by GraphQL-Ruby
module Types
  # The UserType is the GraphQL type for the User model
  class UserType < Types::BaseObject
    description 'A user represents someone that may interact with this API.'
    field :id, ID, null: false
    field :firstName, String, null: false
    field :lastName, String, null: false
    field :email, String, null: false
    field :balance, Float, null: false
    field :imageCount, Integer, null: false
    field :images, [Types::ImageType], null: false
    field :purchases, [Types::PurchaseType], null: false
  end

  def images
    Loaders::HasManyLoader.for(Image, :images).load(object)
  end

  def purchases
    Loaders::HasManyLoader.for(Purchase, :purchases).load(object)
  end
end
