
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: db #uncomment this if using docker-compose

development:
  <<: *default
  database: image_repository_development
  username: postgres
  password: 1234

test:
  <<: *default
  database: image_repository_test
  username: postgres
  password: 1234

production:
  <<: *default
  database: image_repository_production
  username: image_repository
  password: <%= ENV['IMAGE_REPOSITORY_DATABASE_PASSWORD'] %>
