
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: image_repository_development

test:
  <<: *default
  database: image_repository_test

production:
  <<: *default
  database: image_repository_production
  username: image_repository
  password: <%= ENV['IMAGE_REPOSITORY_DATABASE_PASSWORD'] %>
